# Generated by Django 4.1.3 on 2022-12-02 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('day', models.CharField(choices=[('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08'), ('09', '09'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31')], default='01', max_length=2, verbose_name='День')),
                ('month', models.CharField(choices=[('01', 'Январь'), ('02', 'Февраль'), ('03', 'Март'), ('04', 'Апрель'), ('05', 'Май'), ('06', 'Июнь'), ('07', 'Июль'), ('08', 'Август'), ('09', 'Сентябрь'), ('10', 'Октябрь'), ('11', 'Ноябрь'), ('12', 'Декабрь')], default='01', max_length=2, verbose_name='Месяц')),
                ('year', models.PositiveSmallIntegerField(default=2023, verbose_name='Год')),
                ('timeHour', models.CharField(choices=[('00', '00'), ('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08'), ('09', '09'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23')], default='00', max_length=2, verbose_name='Час начала')),
                ('timeMinute', models.PositiveSmallIntegerField(verbose_name='Минута начала')),
                ('place', models.CharField(max_length=250, verbose_name='Место проведения')),
                ('place_link', models.CharField(max_length=250, verbose_name='Ссылка на место')),
                ('guest', models.PositiveSmallIntegerField(verbose_name='Количество гостей')),
                ('timeDuration', models.PositiveSmallIntegerField(verbose_name='Длительность мероприятия')),
                ('dress_style', models.CharField(max_length=40, verbose_name='Дресс-код')),
                ('price', models.IntegerField(verbose_name='Новая Цена')),
                ('oldprice', models.IntegerField(verbose_name='Старая Цена')),
                ('procents', models.IntegerField(verbose_name='Скидка Процентов')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
    ]
