# Generated by Django 4.1.3 on 2022-12-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_event_timeminute'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_About_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(default='0', max_length=250, verbose_name='Ссылка на подробнее')),
            ],
        ),
        migrations.CreateModel(
            name='Event_About_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(default='0', max_length=250, verbose_name='Ссылка на подробнее')),
            ],
        ),
        migrations.CreateModel(
            name='Event_About_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(default='0', max_length=250, verbose_name='Ссылка на подробнее')),
            ],
        ),
    ]
