# Generated by Django 4.1.3 on 2022-12-02 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_event_about_1_event_about_2_event_about_3'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event_About_1',
            new_name='Event_About',
        ),
        migrations.DeleteModel(
            name='Event_About_2',
        ),
        migrations.DeleteModel(
            name='Event_About_3',
        ),
    ]
