# Generated by Django 4.1.3 on 2022-12-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_event_about_2_event_about_3_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event_About_1',
        ),
        migrations.DeleteModel(
            name='Event_About_2',
        ),
        migrations.DeleteModel(
            name='Event_About_3',
        ),
        migrations.AddField(
            model_name='event',
            name='link1',
            field=models.CharField(default='0', max_length=250, verbose_name='Ссылка на подробнее'),
        ),
        migrations.AddField(
            model_name='event',
            name='link2',
            field=models.CharField(default='0', max_length=250, verbose_name='Ссылка на подробнее'),
        ),
        migrations.AddField(
            model_name='event',
            name='link3',
            field=models.CharField(default='0', max_length=250, verbose_name='Ссылка на подробнее'),
        ),
        migrations.AddField(
            model_name='event',
            name='link4',
            field=models.CharField(default='0', max_length=250, verbose_name='Ссылка на подробнее'),
        ),
        migrations.AddField(
            model_name='event',
            name='link5',
            field=models.CharField(default='0', max_length=250, verbose_name='Ссылка на подробнее'),
        ),
        migrations.AddField(
            model_name='event',
            name='link6',
            field=models.CharField(default='0', max_length=250, verbose_name='Ссылка на подробнее'),
        ),
        migrations.AddField(
            model_name='event',
            name='link7',
            field=models.CharField(default='0', max_length=250, verbose_name='Ссылка на подробнее'),
        ),
        migrations.AddField(
            model_name='event',
            name='link8',
            field=models.CharField(default='0', max_length=250, verbose_name='Ссылка на подробнее'),
        ),
    ]
