# Generated by Django 4.1.3 on 2022-12-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_event_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='lendingLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link1', models.CharField(max_length=250, verbose_name='Ссылка баннер')),
                ('link2', models.CharField(max_length=250, verbose_name='Ссылка ноутбук')),
            ],
            options={
                'verbose_name': 'Ссылка',
                'verbose_name_plural': 'Ссылки',
            },
        ),
    ]
