# Generated by Django 4.1.3 on 2022-12-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_lendinglinks_link1_alter_lendinglinks_link2'),
    ]

    operations = [
        migrations.AddField(
            model_name='lendinglinks',
            name='title',
            field=models.CharField(default='name', max_length=50, verbose_name='Название'),
        ),
    ]
