# Generated by Django 4.1.3 on 2023-05-09 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_docs_partner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='oldprice',
        ),
    ]
